version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "security-team"
    assignees:
      - "security-team"
    commit-message:
      prefix: "🔒 [Security]"
      include: "scope"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    versioning-strategy: increase

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "🚀 [CI]"
      include: "scope"
